apiVersion: v1
kind: Service
metadata:
  name: mongo-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mongo  # Replace with your MongoDB app label if necessary
  ports:
    - port: 27017
      targetPort: 27017