package constants

const (
	SERVICE_CODE = "PRODUCTS_SERVICE"

	MANAGEMENT_SERVICE_CODE = "PRODUCTS_MANAGEMENT_SERVICE"

	UNICOM_API_CODE = "UNICOM_SALTY"

	EXPORT_JOB_CODE = "export_job_code"

	// API Codes
	API_CODE_UNICOM_FETCH_PRODUCTS    = "FETCH_PRODUCTS"
	API_CODE_UNICOM_CREATE_JOB        = "CREATE_EXPORT_JOB"
	API_CODE_UNICOM_EXPORT_JOB_STATUS = "EXPORT_JOB_STATUS"
	API_CODE_GET_INVENTORY_SNAPSHOT   = "GET_INVENTORY_SNAPSHOT"
	API_CODE_ADJUST_INVENTORY         = "ADJUST_INVENTORY"
)
